binary_sensor:
- platform: ping
  name: VPN_status
  host: !secret ping_vpn_status_hostip
- platform: mqtt
  name: iotlink_brontosaurus_connected
  state_topic: "iotlink/workgroup/brontosaurus/lwt"
  value_template: "{{ value }}"
  payload_on: "ON"
  payload_off: "OFF"
  device_class: "connectivity"
  qos: 1
- platform: mqtt
  name: iotlink_velociraptor_connected
  state_topic: "iotlink/workgroup/velociraptor/lwt"
  value_template: "{{ value }}"
  payload_on: "ON"
  payload_off: "OFF"
  device_class: "connectivity"
  qos: 1
- platform: huesensor

