switch:
- platform: wake_on_lan
  mac: !secret velociraptor_mac
  name: Velociraptor
  host: !secret velociraptor_host_ip
  turn_off:
    service: hassio.addon_stdin
    data:
      addon: core_rpc_shutdown
      input: Velociraptor
- platform: wake_on_lan
  mac: !secret brontosaurus_mac
  name: Brontosaurus
  host: !secret brontosaurus_host_ip
  turn_off:
    service: hassio.addon_stdin
    data:
      addon: core_rpc_shutdown
      input: Brontosaurus
- platform: wake_on_lan
  mac: !secret allosaurus_mac
  name: Allosaurus
  host: !secret allosaurus_host_ip
  turn_off:
    service: hassio.addon_stdin
    data:
      addon: core_rpc_shutdown
      input: Allosaurus
- platform: wake_on_lan
  mac: !secret triceratops_mac
  name: Triceratops
  host: !secret triceratops_host_ip
- platform: mqtt
  name: "Sonoff Basic 1"
  state_topic: "tasmota/sonoff_basic_1/stat/POWER"
  command_topic: "tasmota/sonoff_basic_1/cmnd/POWER"
  availability_topic: "tasmota/sonoff_basic_1/tele/LWT"
  qos: 1
  payload_on: "ON"
  payload_off: "OFF"
  payload_available: "Online"
  payload_not_available: "Offline"
  retain: false
#- platform: mqtt
#  name: "Sonoff Basic 2"
#  state_topic: "tasmota/sonoff_basic_2/stat/POWER"
#  command_topic: "tasmota/sonoff_basic_2/cmnd/POWER"
#  availability_topic: "tasmota/sonoff_basic_2/tele/LWT"
#  qos: 1
#  payload_on: "ON"
#  payload_off: "OFF"
#  payload_available: "Online"
#  payload_not_available: "Offline"
#  retain: false
- platform: mqtt
  name: "Sonoff 4CH 1"
  state_topic: "tasmota/sonoff_4ch/stat/POWER1"
  command_topic: "tasmota/sonoff_4ch/cmnd/POWER1"
  availability_topic: "tasmota/sonoff_4ch/tele/LWT"
  qos: 1
  payload_on: "ON"
  payload_off: "OFF"
  payload_available: "Online"
  payload_not_available: "Offline"
  retain: false
- platform: mqtt
  name: "Sonoff 4CH 2"
  state_topic: "tasmota/sonoff_4ch/stat/POWER2"
  command_topic: "tasmota/sonoff_4ch/cmnd/POWER2"
  availability_topic: "tasmota/sonoff_4ch/tele/LWT"
  qos: 1
  payload_on: "ON"
  payload_off: "OFF"
  payload_available: "Online"
  payload_not_available: "Offline"
  retain: false
- platform: mqtt
  name: "Sonoff 4CH 3"
  state_topic: "tasmota/sonoff_4ch/stat/POWER3"
  command_topic: "tasmota/sonoff_4ch/cmnd/POWER3"
  availability_topic: "tasmota/sonoff_4ch/tele/LWT"
  qos: 1
  payload_on: "ON"
  payload_off: "OFF"
  payload_available: "Online"
  payload_not_available: "Offline"
  retain: false
- platform: mqtt
  name: "Sonoff 4CH 4"
  state_topic: "tasmota/sonoff_4ch/stat/POWER4"
  command_topic: "tasmota/sonoff_4ch/cmnd/POWER4"
  availability_topic: "tasmota/sonoff_4ch/tele/LWT"
  qos: 1
  payload_on: "ON"
  payload_off: "OFF"
  payload_available: "Online"
  payload_not_available: "Offline"
  retain: false
- platform: mqtt
  name: "Shelly 1"
  state_topic: "tasmota/shelly_1/stat/POWER"
  command_topic: "tasmota/shelly_1/cmnd/POWER"
  availability_topic: "tasmota/shelly_1/tele/LWT"
  qos: 1
  payload_on: "ON"
  payload_off: "OFF"
  payload_available: "Online"
  payload_not_available: "Offline"
  retain: false
#- platform: broadlink
#  host: !secret broadlink_host_ip
#  mac: !secret broadlink_mac
#  timeout: 15