title: Jurassic
views:
- !include lovelace/00_overview.yaml
- !include lovelace/30_overview_short.yaml
- !include lovelace/10_lights.yaml
- !include lovelace/15_sensors.yaml
- !include lovelace/20_machines.yaml
