custom_header:
  compact_mode: true
  menu: overflow
  hide_help: true
  options: clock
  voice: hide
  clock_format: 24
  exceptions:
  - conditions:
      user: katrin
    config:
      options: clock
      clock_format: 24
      hide_tabs: 
        - 0
        - 3
  - conditions:
      user: D3lta3
    config:
      options: clock
      clock_format: 24
      hide_tabs:
        - 4
  - conditions:
      user: d3lta3
    config:
      options: clock
      lock_format: 24
      hide_tabs:
        - 4

title: Jurassic
views:
- !include lovelace/00_overview.yaml
- !include lovelace/10_lights.yaml
- !include lovelace/15_sensors.yaml
- !include lovelace/20_machines.yaml
- !include lovelace/30_overview_short.yaml